name: WarPracticeCore
version: '1.0.0'
main: dev.zoid.warpracticecore.WarPracticeCore
api-version: '1.21'
authors: [ Zoid ]
description: Core plugin for war practice
commands:
  ping:
    aliases: [p]
  spawn:
    usage: /<command>
  tier:
    usage: /<command> <get/set> <player> <tier>
    permission: warpractice.tier
  setspawn:
    permission: warpractice.setspawn
  rtp:
    usage: /rtp
  rtpqueue:
    usage: /rtpqueue
  tpa:
    usage: /tpa
  tpahere:
    usage: /tpahere
  tpdeny:
    usage: /tpdeny
  tpacancel:
    usage: /tpcancel
  tpaccept:
    usage: /tpaccept
  back:
    usage: /back
  box:
    usage: /box
  flat:
    usage: /flat
  discord:
    usage: /discord
  tierlist:
    usage: /tierlist
  region:
    usage: /region
    permission: warpracticecore.region
  broadcast:
    usage: /<command> <args.length == >1>
    permission: warpractice.broadcast
    aliases: [bc, announce]
  event:
    usage: /<command>
  eventannounce:
    usage: /<command>
    permission: warpractice.event.announce
  eventstop:
    usage: /<command>
    permission: warpractice.event.stop
  eventstart:
    usage: /<command>
    permission: warpractice.event.start
  eventannouncecancel:
    usage: /<command>
    permission: warpractice.event.announcecancel